### ISSUE TITLE
Using with phone camera

### ISSUE THREAD

**Issue by amir989** [fuziki/VideoCreator#22]
Hey, Thanks a lot for the plugin. Your demo is working fine when I build on my iPad. I'm using NatCore plugin to work with the camera and when I `StartRecMovWithAudio()` it seems the textures are being captured by looking at Xcode! but when I call `FinishRec() ` the whole thing freeze and I get this error in Xcode. 

> UnityVideoCreator/MediaSaver.swift:14: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"
```

UnityVideoCreator/MediaSaver.swift:14: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"
Message from debugger: failed to send the k packet
```

I was hoping if you could tell what is causing the problem. 

Thank you!

**Comment by fuziki** [comment]
Thanks for the asking.
I have no knowledge of the NatCore plugin, so this may not be an appropriate answer.
Looks like it is failed to create the video.
If you want to use the device's camera, I recommend using [WebCamTexture](https://docs.unity3d.com/ja/current/ScriptReference/WebCamTexture.html).

**Comment by amir989** [comment]
Hi again. Thank you for reply. I found the solution. it seems the renderTexture resolution has to be fix and cant be change during runtime even if the recording hasn't started. and it also cannot be used as texture for a material that is being overridden. It works fine on my iPad. 

Now I'm trying to push the app for test flight. but get the below error when I'm trying to Archive the app in Xcode: 

`bitcode bundle could not be generated because '/Users/xxxx/Desktop/Projects/xxxx/Build/Frameworks/Plugin/VideoCreator/Plugins/iOS/UnityVideoCreator.framework/UnityVideoCreator' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/xxxx/Desktop/Projects/xxxx/Build/Frameworks/Plugin/VideoCreator/Plugins/iOS/UnityVideoCreator.framework/UnityVideoCreator' for architecture arm64`

I changed the plugin in unity to arm64 and I restarted Unity. I also ran the file in the directory mentioned in the error. But it didnt fix it. any suggestion? 

Thank you.

**Comment by fuziki** [comment]
Made a Pull Request to enable bitcode. https://github.com/fuziki/VideoCreator/pull/23
Try to use this branch to archive.

Alternatively, disable bitcode for xcode projects built with Unity, maybe you can archive them.

Thank you.

**Comment by amir989** [comment]
Thanks a bunch for solving it quick. I am able to archive now. and big like on your awesome plugin :)

**Comment by fuziki** [comment]
Thanks for checking!
If your app is published in the app store, I' m happy to know about it.
I hope your project goes well.
