### ISSUE TITLE
Screen Recording in Unity for iOS

### ISSUE THREAD

**Issue by procw** [fuziki/VideoCreator#4]
Thanks for your project.
I wanna screen recording in Unity for iOS using your project, but I can't result in iphoneX Max.
I built https://github.com/fuziki/VideoCreator/tree/master/ZUnityProject/VideoCreator in Unity and open, run in Xcode.
Build succeeded, but the app crashes.
Can you tell me good guide about your project build method or other method?
Also can I get the *.mp4 in iOS using your project?

**Comment by fuziki** [comment]
Thanks for the asking.
Can you run a committed Xcode Project?
This project was created by building the Unity example.
You do not need to build in Unity to run this project.
https://github.com/fuziki/VideoCreator/tree/master/ZUnityProject/build/VideoCreatorIOS

* If you can run this project, you need to check the configuration of Unity and the Xcode Project you built.
* If you can' t run this project, tell the error you are getting.
