### ISSUE TITLE
Video player

### ISSUE THREAD

**Issue by amir989** [fuziki/VideoCreator#45]
Hi there,

Great plugin. We ran to this issue that the unity video player stops playing video, when we try to record video and sound with your plugin! I was wondering if you know the reason? 

Also, another question. What is the end goal of your plugin? is this something that you are planing to support long term?  and what are the next features that you are planning to add. I would be more than happy to help on Unity side if you need a hand. 

Thanks.

**Comment by fuziki** [comment]
Hello, thank you for the asking.

> I was wondering if you know the reason?

I'm sorry, but I don't know the reason either.

> another question

I don't have a set goal for this project.
However, I will be implementing new features.
Check the issue for planned features.
Contributions for issues and pull requests are always welcome.

Regards,
