### ISSUE TITLE
Crash when rotate CMSampleBuffer portrait to landcape

### ISSUE THREAD

**Issue by thachonline** [fuziki/VideoCreator#47]
When I switch from portrait to landscape and vice versa.
With HLSExample, is there a way to roate 1 CMSampleBuffer and write it.
Also in the example is there a way to change the width and height while writing?

**Comment by fuziki** [comment]
Thanks for the report.
There is no way to change the size of the video while streaming.
I plan to prevent crashes by checking the texture format.
