### ISSUE TITLE
Only white screen

### ISSUE THREAD

**Issue by vinayvidhani** [fuziki/VideoCreator#8]
I used your plugin but I got white screen only and Its not valid video. 
Next I tried to change its extension from .mov to .mp4 then I found only audio I am getting.

Edited : How I am saying this is not a valid video, When I tried to share the video then I got popup message, You cannot share this video because its invalid.

**Comment by fuziki** [comment]
Thanks for the asking.
First, I suggest that you make sure that you are sending the correct texture.
Check the sample project and copy the texture settings.
